sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

matrix:
  fast_finish: true
  include:
    - php: 5.3
      dist: precise
      env: COMPOSER_OPTIONS="--prefer-lowest --prefer-stable"
    - php: 7.2
      env: deps="high"

before_install:
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then phpenv config-rm xdebug.ini; fi
  - composer self-update

install:
  - if [ "$deps" = "high" ]; then composer config minimum-stability dev; fi
  - composer update $COMPOSER_OPTIONS

script:
  - php validate.php
